export const ERROR_CODES = {
  EMPTY_CSV: "EMPTY_CSV",
  INVALID_HEADERS: "INVALID_HEADERS",
  NO_VALID_RECORDS: "NO_VALID_RECORDS",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  NO_FILE_UPLOADED: "NO_FILE_UPLOADED",
} as const;